

export const techStackData = {
    'front-end': [
        { name: 'HTML', icon: '/images/html.svg' },
        { name: 'CSS', icon: '/images/css.svg' },
        { name: 'Javascript', icon: '/images/javascript.svg' },
        { name: 'SaaS', icon: '/images/sass.svg' },
        { name: 'React JS', icon: '/images/react.svg' },
        { name: 'Vue JS', icon: '/images/vue.svg' },
        { name: 'Angular', icon: '/images/angular.svg' },
        { name: 'Meteor JS', icon: '/images/meteor.svg' },
        { name: 'Nuxt JS', icon: '/images/nuxt.svg' },
        { name: 'WebGL', icon: '/images/webgl.svg' },
    ],
    'back-end': [
        { name: 'Node-js', icon: '/images/nodejs.svg' },
        { name: 'Python', icon: '/images/python.svg' },
        { name: 'Elixir', icon: '/images/elixir.svg' },
        { name: 'Ruby', icon: '/images/ruby.svg' },
        { name: 'Java', icon: '/images/java.svg' },
        { name: 'php', icon: '/images/php.svg' },
        { name: 'Golang', icon: '/images/golang.svg' },
        { name: 'C#', icon: '/images/csharp.svg' },
        { name: 'C++', icon: '/images/cplusplus.svg' },
        { name: 'Rust', icon: '/images/rust.svg' },
        { name: 'Nest-js', icon: '/images/nestjs.svg' },
        { name: '.Net Core', icon: '/images/dotnet.svg' },
    ],
    'low-no-code': [
        { name: 'Shopify', icon: '/images/shopify.svg' },
        { name: 'Wordpress', icon: '/images/wordpress.svg' },
        { name: 'Strapi', icon: '/images/strapi.svg' },
        { name: 'bubble.io', icon: '/images/bubble.svg' },
        { name: 'builder.io', icon: '/images/builder.svg' },
        { name: 'Zoho', icon: '/images/zoho.svg' },
        { name: 'Zapier', icon: '/images/zapier.svg' },
        { name: 'Webflow', icon: '/images/webflow.svg' },
        { name: 'Wix', icon: '/images/wix.svg' },
        { name: "Wizard's Toolkit", icon: '/images/wizard-toolkit.svg' },
    ],
    'database': [
        { name: 'Firebase', icon: '/images/firebase.svg' },
        { name: 'Mongodb', icon: '/images/mongodb.svg' },
        { name: 'Postgresql', icon: '/images/postgresql.svg' },
        { name: 'Couch-db', icon: '/images/couchdb.svg' },
        { name: 'Db', icon: '/images/db.svg' },
        { name: 'Sqlite', icon: '/images/sqlite.svg' },
        { name: 'Ms-sql', icon: '/images/mssql.svg' },
        { name: 'Aws-dynamodb', icon: '/images/dynamodb.svg' },
        { name: 'Oracle', icon: '/images/oracle.svg' },
        { name: 'Mysql', icon: '/images/mysql.svg' },
        { name: 'Redis', icon: '/images/redis.svg' },
    ],
    'devops': [
        { name: 'Aws', icon: '/images/aws.svg' },
        { name: 'Gcp', icon: '/images/gcp.svg' },
        { name: 'Azure', icon: '/images/azure.svg' },
        { name: 'Ibm-cloud', icon: '/images/ibm-cloud.svg' },
        { name: 'Digital-ocean', icon: '/images/digital-ocean.svg' },
        { name: 'Oracle-cloud', icon: '/images/oracle-cloud.svg' },
        { name: 'Puppet', icon: '/images/puppet.svg' },
        { name: 'Kubernetes', icon: '/images/kubernetes.svg' },
        { name: 'Docker', icon: '/images/docker.svg' },
        { name: 'Jenkins', icon: '/images/jenkins.svg' },
        { name: 'Chef', icon: '/images/chef.svg' },
        { name: 'Terraform', icon: '/images/terraform.svg' },
    ],
    'mobile': [
        { name: 'Android', icon: '/images/android.svg' },
        { name: 'Kotlin', icon: '/images/kotlin.svg' },
        { name: 'Swift', icon: '/images/swift.svg' },
        { name: 'Objective-c', icon: '/images/objective-c.svg' },
        { name: 'React-native', icon: '/images/react-native.svg' },
        { name: 'Ionic', icon: '/images/ionic.svg' },
        { name: 'Flutter', icon: '/images/flutter.svg' },
        { name: 'IoS', icon: '/images/ios.svg' },
        { name: 'Pwa', icon: '/images/pwa.svg' },
    ],
    'ai-ml': [
        { name: 'Tensorflow', icon: '/images/tensorflow.svg' },
        { name: 'Keras', icon: '/images/keras.svg' },
        { name: 'Pytorch', icon: '/images/pytorch.svg' },
        { name: 'Lisp', icon: '/images/lisp.svg' },
        { name: 'NTKL', icon: '/images/nltk.svg' },
        { name: 'SpaCy', icon: '/images/spacy.svg' },
        { name: 'Open-ai', icon: '/images/openai.svg' },
        { name: 'Ploty', icon: '/images/plotly.svg' },
        { name: 'Matplotlib', icon: '/images/matplotlib.svg' },
        { name: 'Pandas', icon: '/images/pandas.svg' },
        { name: 'Opencv', icon: '/images/opencv.svg' },
        { name: 'Numpy', icon: '/images/numpy.svg' },
        { name: 'Scikit_learn', icon: '/images/scikit-learn.svg' },
        { name: 'Mistral', icon: '/images/mistral.svg' },
        { name: 'DeepSeek', icon: '/images/deepseek.svg' },
        { name: 'llamas', icon: '/images/llamas.svg' },
        { name: 'Langflow', icon: '/images/langflow.svg' },
    ],
};

// Create the 'all' category by combining the arrays of all other categories
const allTech = Object.values(techStackData).flat();
techStackData.all = allTech;